<?php

namespace Tests\Feature;

use App\Links\CompressedLink;
use App\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\Response;
use Illuminate\Support\Collection;
use Tests\TestCase;

class ApiLinkControllerTest extends TestCase
{
    use DatabaseTransactions;

    /**
     * @var Collection
     */
    private $links;

    /**
     * @var User
     */
    private $user;

    /**
     * @var User
     */
    private $wrongUser;

    /**
     * @var Collection
     */
    private $wrongLinks;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
        $this->wrongUser = factory(User::class)->create();
        $this->actingAs($this->user, 'api');
        $this->links = factory(CompressedLink::class, 3)->make()->each(function (CompressedLink $link) {
            $link->user()->associate($this->user)->save();
        });

        $this->wrongLinks = factory(CompressedLink::class, 3)->make()->each(function (CompressedLink $link) {
            $link->user()->associate($this->wrongUser)->save();
        });

    }

    public function testIndex()
    {
        $response = $this->get('/api/links');
        $response->assertOk();
        $payload = $response->decodeResponseJson()['data'];
        $this->assertEquals($this->links->count(), count($payload));
    }

    public function testGet()
    {
        $response = $this->get('/api/links/' . $this->links->first()->id);
        $response->assertOk();
        $payload = $response->decodeResponseJson()['data'];
        $this->assertEquals($this->links->first()->link, $payload['link']);
    }

    public function testPost()
    {
        $response = $this->post('/api/links', ['link' => 'testword']);
        $this->assertEquals(Response::HTTP_CREATED, $response->getStatusCode());
    }

    public function testPut()
    {
        $updateValue = 'testword';
        $response = $this->get('/api/links/' . $this->links->first()->id);
        $response->assertOk();
        $link = $response->decodeResponseJson()['data'];
        $link['link'] = $updateValue;

        $response = $this->put('/api/links/' . $this->links->first()->id, $link);
        $response->assertOk();
        $link = $response->decodeResponseJson()['data'];
        $this->assertEquals($updateValue, $link['link']);
    }

    public function testDelete()
    {
        $response = $this->delete('/api/links/' . $this->links->first()->id);
        $response->assertOk();

        $response = $this->get('/api/links/' . $this->links->first()->id);
        $this->assertEquals(Response::HTTP_NOT_FOUND, $response->getStatusCode());
    }

    public function testWrongGet()
    {
        $response = $this->get('/api/links/' . ($this->links->first()->id + 1000));
        $this->assertEquals(Response::HTTP_NOT_FOUND, $response->getStatusCode());
    }

    public function testWrongPost()
    {
        $response = $this->post('/api/links', ['link' => str_repeat('testword', 1000)]);
        $this->assertEquals(Response::HTTP_BAD_REQUEST, $response->getStatusCode());
    }

    public function testWrongPut()
    {
        $updateValue = str_repeat('testword', 1000);
        $response = $this->get('/api/links/' . $this->links->first()->id);
        $response->assertOk();
        $link = $response->decodeResponseJson()['data'];
        $link['link'] = $updateValue;

        $response = $this->put('/api/links/' . $this->links->first()->id, $link);
        $this->assertEquals(Response::HTTP_BAD_REQUEST, $response->getStatusCode());
    }

    public function testWrongDelete()
    {
        $response = $this->delete('/api/links/' . ($this->links->first()->id + 1000));
        $this->assertEquals(Response::HTTP_NOT_FOUND, $response->getStatusCode());
    }

}
